FROM nvidia/cuda:8.0-cudnn5-devel

MAINTAINER Shawn Chen <kertansul@gmail.com>

######################################################################
# Torch install
######################################################################

RUN apt-get update
RUN apt-get install -y git

RUN cd /home
RUN git clone https://github.com/kuz/DeepMind-Atari-Deep-Q-Learner.git

RUN cd DeepMind-Atari-Deep-Q-Learner
