FROM jenkins

# if we want to install via apt
USER root

RUN apt-get update

RUN apt-get install -y sudo \
                       vim \
                       rsync

# drop back to the regular jenkins user - good practice
USER jenkins

ENTRYPOINT ./usr/local/bin/jenkins.sh && /bin/bash
