FROM jenkins

# if we want to install via apt
USER root

RUN apt-get update

RUN apt-get install -y sudo \
                       vim \
                       rsync

ENTRYPOINT ./usr/local/bin/jenkins.sh && /bin/bash
