FROM nvidia/cuda:8.0-cudnn5-devel-ubuntu14.04

MAINTAINER Shawn Chen <kertansul@gmail.com>

RUN apt-get install software-properties-common
RUN add-apt-repository -y ppa:ethereum/ethereum-qt
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN add-apt-repository ppa:ethereum/ethereum-dev
RUN apt-get update
RUN apt-get install ethereum
RUN apt-get install cpp-ethereum

EXPOSE 30303 8545

WORKDIR "/root"
